name: Job Build and Publish

on:
  workflow_dispatch:
    inputs:
      job-name:
        description: 'Job directory'
        required: true
        type: choice
        options:
          - 'gdc-job'
          - 'passthrough-job'
          - 'kafka-postgres-job'
      
      publish-as-latest:
        description: "Publish as latest version"
        required: true
        type: boolean

      environment:
        description: 'Target environment (selection input for workflow dispatch)'
        required: true
        type: choice
        options:
          - 'dev'
          - 'int'
          - 'pre-eu'
          - 'pre-us'
  
jobs:
  map-envs:
    runs-on: ubuntu-latest
    steps:
    - id: map
      run: |
        case "${{ inputs.environment }}" in
          dev)
            echo "keyvault=111111111111" >> $GITHUB_OUTPUT
            ;;
          int)
            echo "keyvault=22222222222" >> $GITHUB_OUTPUT
            ;;
          pre-eu)
            echo "keyvault=33333333333" >> $GITHUB_OUTPUT
            ;;
          pre-us)
            echo "keyvault=44444444444" >> $GITHUB_OUTPUT
            ;;
        esac
    outputs:
      keyvault: ${{ steps.map.outputs.keyvault }}
  finish:
    runs-on: ubuntu-latest
    needs: map-envs
    steps:
    - id: output
      run: |
          echo "AZ_KEYVAULT=${{ needs.map-envs.outputs.keyvault }}" >> $GITHUB_OUTPUT

 
